### ISSUE TITLE
The game "140" don’t install 

### ISSUE THREAD

**Issue by trinukso** [Heroic-Games-Launcher/heroic-gogdl#56]
It is impossible to install the native version.

Flatpak version. Gnome on Archlinux. Thanks.

![Captura desde 2024-10-03 10-48-25](https://github.com/user-attachments/assets/8f7628f5-1ca2-433a-8d63-d972785e09f6)

**Comment by imLinguin** [comment]
fixed in https://github.com/Heroic-Games-Launcher/heroic-gogdl/commit/53964bd099d3078ec3f0a6a365f67eaecf01dbc4

could you test it? The pipeline should finish shortly, https://github.com/Heroic-Games-Launcher/heroic-gogdl/actions/runs/11162353124

- get ubuntu zip, and extract it
- make gogdl executable
- select it in Heroic advanced settings

**Comment by trinukso** [comment]
Works! Thanks! 

![imagen](https://github.com/user-attachments/assets/d745742b-87ee-4529-aa9f-82dc4300ba61)
![imagen](https://github.com/user-attachments/assets/60dbd308-9e66-48be-a902-2ad7fd8da336)
